version: "3.8"

services:
  ### Laravel Backend ###
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    depends_on:
      - mysql

  ### Laravel Nginx ###
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  ### MySQL Database ###
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  ### React Frontend ###
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
